# Generated by Django 5.1.7 on 2026-01-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_award_links_certificate_links_image_links_page_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='link',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
        migrations.RemoveField(
            model_name='page',
            name='link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_repo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='link',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='link',
        ),
    ]
